import{a as h,i as b,S as L}from"./assets/vendor-0Fq3u7cb.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const w="45358562-a6f601b45a643dd81cb1b87d3",E="https://pixabay.com/api/";async function $(t,o=1,a=15){const n=`${E}?key=${w}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${a}`;try{return(await h.get(n)).data}catch{throw new Error("Failed to fetch images")}}function B(t){const o=document.getElementById("gallery"),a=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:y,comments:p,downloads:g})=>`
        <a href="${e}" class="gallery-item">
            <img src="${n}" alt="${r}" />
            <div class="info">
                <p>Likes: ${i}</p>
                <p>Views: ${y}</p>
                <p>Comments: ${p}</p>
                <p>Downloads: ${g}</p>
            </div>
        </a>`).join("");o.insertAdjacentHTML("beforeend",a)}function c(t){b.error({title:"Error",message:t,position:"topRight"})}function I(){document.getElementById("gallery").innerHTML=""}function u(t){const o=document.getElementById("load-more");o.style.display=t?"block":"none"}let l,s=1,d="";const f=document.querySelector("#loader"),v=document.getElementById("load-more");document.querySelector("#search-form").addEventListener("submit",async function(t){if(t.preventDefault(),d=document.getElementById("search-input").value.trim(),d===""){c("Search field cannot be empty.");return}s=1,I(),u(!1),await m()});v.addEventListener("click",async()=>{s++,await m()});async function m(){S();try{const t=await $(d,s);if(t.hits.length>0){B(t.hits),P();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),u(s*15<t.totalHits),s*15>=t.totalHits&&c("We're sorry, but you've reached the end of search results.")}else c("Sorry, there are no images matching your search query. Please try again!")}catch(t){c(t.message)}finally{M()}}function S(){f.style.display="block"}function M(){f.style.display="none"}function P(){l?l.refresh():l=new L(".gallery-item",{captionsData:"alt",captionDelay:250})}
//# sourceMappingURL=commonHelpers.js.map
